# Generated by Django 3.0.12 on 2021-02-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id_account',
            field=models.BigIntegerField(default='NotInGroup', error_messages={'unique': 'Esta identificación de usuario ya está registrada'}, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(error_messages={'unique': 'Este nombre de usuario ya está registrado'}, max_length=40, unique=True),
        ),
    ]
