# Generated by Django 3.0.12 on 2021-02-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20210217_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id_account',
            field=models.BigIntegerField(error_messages={'unique': 'Esta identificación de usuario ya está registrada'}, primary_key=True, serialize=False),
        ),
    ]
