# Generated by Django 3.0.12 on 2021-02-19 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Skill', '0001_initial'),
        ('Files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Event', '0001_initial'),
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventuser',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='entries',
            field=models.ManyToManyField(through='Event.EventUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='id_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location.City'),
        ),
        migrations.AddField(
            model_name='event',
            name='id_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Files.Files'),
        ),
        migrations.AddField(
            model_name='event',
            name='id_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.StateEvent'),
        ),
        migrations.AddField(
            model_name='event',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='skills',
            field=models.ManyToManyField(to='Skill.Skill'),
        ),
    ]
